# Day 15

# Pandas (Part 2 )

In [2]:
import pandas as pd

In [7]:

df = pd.read_csv("titanic.csv")

In [8]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [10]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [18]:
df['Name'][0:11]

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
Name: Name, dtype: str

In [19]:
a = df['Name'][0:11]

In [22]:
a

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
Name: Name, dtype: str

In [23]:
type(a)

pandas.Series

In [32]:
l = ['A1','A2','A3',"A4",'A5','A6','A7','A8','A9','A10', 'A11']

In [29]:
pd.Series(a,index = l)

A1     NaN
A2     NaN
A3     NaN
A4     NaN
A5     NaN
A6     NaN
A7     NaN
A8     NaN
A9     NaN
A10    NaN
Name: Name, dtype: str

In [33]:
pd.Series (list(a), index = l)

A1                               Braund, Mr. Owen Harris
A2     Cumings, Mrs. John Bradley (Florence Briggs Th...
A3                                Heikkinen, Miss. Laina
A4          Futrelle, Mrs. Jacques Heath (Lily May Peel)
A5                              Allen, Mr. William Henry
A6                                      Moran, Mr. James
A7                               McCarthy, Mr. Timothy J
A8                        Palsson, Master. Gosta Leonard
A9     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
A10                  Nasser, Mrs. Nicholas (Adele Achem)
A11                      Sandstrom, Miss. Marguerite Rut
dtype: str

In [56]:
m1 = pd.Series([100,200,300,400,500], index = [1,2,3,4,5])

In [57]:
m1

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [49]:
m2 = pd.Series([600,700,800,900,1000], index = [1,2,3,4,5])

In [39]:
m2

1     600
2     700
3     800
4     900
5    1000
dtype: int64

In [59]:
m3 = pd.concat([m1,m2],ignore_index = True)

In [60]:
m3

0     100
1     200
2     300
3     400
4     500
5     600
6     700
7     800
8     900
9    1000
dtype: int64

In [61]:
m3[1]

np.int64(200)

In [62]:
m4 = m1*m2

In [63]:
m4

1     60000
2    140000
3    240000
4    360000
5    500000
dtype: int64

In [64]:
m5 = m1+m2

In [65]:
m5

1     700
2     900
3    1100
4    1300
5    1500
dtype: int64

In [66]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [71]:
df.drop('PassengerId', axis = 1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [72]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [78]:
df.drop('Survived', axis = 1, inplace = True)

<class 'KeyError'>: "['Survived'] not found in axis"

In [77]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [79]:
df.drop(3)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [84]:
df.drop(3, inplace = True)

<class 'KeyError'>: '[3] not found in axis'

In [85]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [87]:
df.set_index('Name', inplace = True)

In [88]:
df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",1,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",5,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",6,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [89]:
df.reset_index()

,Name,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Allen, Mr. William Henry",5,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",6,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",887,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",889,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",891,3,male,32.0,0,0,370376,7.7500,NaN,Q

# Making a dataframe from the dictionary

In [90]:
d = {
    "Key 1" : [1,2,3,4,5],
     "Key 2 " : [6,7,8,9,10],
    "Key 3 ": [11,12,13,14,15]
}
print(d)

{'Key 1': [1, 2, 3, 4, 5], 'Key 2 ': [6, 7, 8, 9, 10], 'Key 3 ': [11, 12, 13, 14, 15]}

In [93]:
pd.DataFrame(d)

   Key 1  Key 2   Key 3
0      1       6      11
1      2       7      12
2      3       8      13
3      4       9      14
4      5      10      15

In [94]:
df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",1,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",5,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",6,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [96]:
df.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   890.000000  890.000000  713.000000  890.000000  890.000000  890.000000
mean    446.496629    2.310112   29.691683    0.522472    0.382022   32.180730
std     257.070995    0.835388   14.535336    1.103247    0.806409   49.716425
min       1.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     224.250000    2.000000   20.000000    0.000000    0.000000    7.903100
50%     446.500000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.750000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [97]:
df.dropna()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"McCarthy, Mr. Timothy J",7,1,male,54.0,0,0,17463,51.8625,E46,S
"Sandstrom, Miss. Marguerite Rut",11,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,female,58.0,0,0,113783,26.5500,C103,S
"Beesley, Mr. Lawrence",22,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",873,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C

In [99]:
df.dropna(inplace = True)

In [100]:
df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"McCarthy, Mr. Timothy J",7,1,male,54.0,0,0,17463,51.8625,E46,S
"Sandstrom, Miss. Marguerite Rut",11,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,female,58.0,0,0,113783,26.5500,C103,S
"Beesley, Mr. Lawrence",22,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",873,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C

In [102]:
df.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   182.000000  182.000000  182.000000  182.000000  182.000000  182.000000
mean    457.846154    1.192308   35.678132    0.461538    0.478022   78.823032
std     245.439123    0.516411   15.686941    0.644701    0.755869   76.534710
min       2.000000    1.000000    0.920000    0.000000    0.000000    0.000000
25%     265.250000    1.000000   24.000000    0.000000    0.000000   29.700000
50%     459.000000    1.000000   36.000000    0.000000    0.000000   57.000000
75%     678.000000    1.000000   47.750000    1.000000    1.000000   90.000000
max     890.000000    3.000000   80.000000    3.000000    4.000000  512.329200

In [103]:
df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"McCarthy, Mr. Timothy J",7,1,male,54.0,0,0,17463,51.8625,E46,S
"Sandstrom, Miss. Marguerite Rut",11,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,female,58.0,0,0,113783,26.5500,C103,S
"Beesley, Mr. Lawrence",22,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",873,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C

In [104]:
df.dropna(axis = 1)

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"McCarthy, Mr. Timothy J",7,1,male,54.0,0,0,17463,51.8625,E46,S
"Sandstrom, Miss. Marguerite Rut",11,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,female,58.0,0,0,113783,26.5500,C103,S
"Beesley, Mr. Lawrence",22,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",873,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C

In [120]:
df.fillna('Not applicable', inplace = True)

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"McCarthy, Mr. Timothy J",7,1,male,54.0,0,0,17463,51.8625,E46,S
"Sandstrom, Miss. Marguerite Rut",11,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,female,58.0,0,0,113783,26.5500,C103,S
"Beesley, Mr. Lawrence",22,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",873,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C

In [121]:
df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"McCarthy, Mr. Timothy J",7,1,male,54.0,0,0,17463,51.8625,E46,S
"Sandstrom, Miss. Marguerite Rut",11,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,female,58.0,0,0,113783,26.5500,C103,S
"Beesley, Mr. Lawrence",22,2,male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",873,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,C